collections:
 - id: specifications
   label: Specifications
   label_single: Specification
   field_map:
     id: specification
     display_name: name
   fields: 
     - { label: "Specification ID (no spaces)", id: "specification", type: "string" }
     - { label: "Specification name", id: "name", type: "string" }
     - { label: "Specification name (plural)", id: "plural", type: "string" }
     - { label: "Specification status", id: "specification-status", type: "string", default_value: "candidate-standard" }
     - { label: "Start date", id: "start-date", type: "date" } 
     - { label: "End date", id: "end-date", type: "date" }
     - { label: "Entry date", id: "entry-date", type: "date", default_value: "now()" }
     - id: "datasets"
       label: "Datasets"
       type: "repeatable"
       fields:
         - { label: "Dataset ID (no spaces)", id: "dataset", type: "string" }
         - { label: "Dataset name", id: "name", type: "string" }
         - id: "fields"
           label: "Fields"
           type: "repeatable"
           fields:
             - { label: "Field", id: "field", type: "string" }
             - { label: "Description", id: "description", type: "text" }
             - { label: "Guidance", id: "guidance", type: "text" }       
 - id: guidance_pages
   label: Guidance pages
   label_single: Guidance page
   field_map:
     id: id
     display_name: title
   fields:
     - { label: "ID", id: "id", type: "string", default_value: "generate_uuid()" }
     - { label: "Title", id: "title", type: "string" }
     - { label: "Body", id: "body", type: "text" }
